/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    DefaultComboBoxModel listmodel;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listmodel = (DefaultComboBoxModel)cb_universos.getModel();
        CargarSeres();
        CargarUniversos();
        if(!s.isEmpty()){
            pb_cargar.setMaximum(s.size());
        }
    }

    private void CargarSeres(){
        try {  
            File se = new File(direGene+"SeresVivos.wal");
            s = new ArrayList();
            Seres t;
            if (se.exists()) {
                  FileInputStream entrada
                    = new FileInputStream(se);
                ObjectInputStream objeto
                    = new ObjectInputStream(entrada);
                try {
                    while ((t = (Seres) objeto.readObject()) != null) {
                        s.add(t);
                    }
                } catch (EOFException e) {
                    //encontro el final del archivo
                }
                objeto.close();
                entrada.close();
            } //fin if           
        } catch (Exception ex) {
            ex.printStackTrace();
        }        
    }
    
    private void CargarUniversos(){
        try {  
            File n = new File(direGene+"Universos.wal");
            u = new ArrayList();
            Universo t;
            if (n.exists()) {
                  FileInputStream entrada
                    = new FileInputStream(n);
                  
                ObjectInputStream objeto
                    = new ObjectInputStream(entrada);
                
                try {
                    while ((t = (Universo) objeto.readObject()) != null) {
                        u.add(t);
                    }
                } catch (EOFException e) {
                    //encontro el final del archivo
                }
                objeto.close();
                entrada.close();
            } //fin if           
        } catch (Exception ex) {
            ex.printStackTrace();
        }         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        menu = new javax.swing.JPanel();
        b_cargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        treexd = new javax.swing.JTree();
        b_guardar = new javax.swing.JButton();
        pb_cargar = new javax.swing.JProgressBar();
        crear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreuni = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombreser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        spinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        tf_anos = new javax.swing.JTextField();
        cb_raza = new javax.swing.JComboBox<>();
        cb_universos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        modificar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tf_anos1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cb_raza1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        tf_nombreser1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_id1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        spin = new javax.swing.JSpinner();
        cb_mof = new javax.swing.JComboBox<>();
        b_modificar = new javax.swing.JButton();
        buscar = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_nombrebuscar = new javax.swing.JTextField();
        tf_idbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        eliminar = new javax.swing.JPanel();
        cb_mof1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        b_cargar.setText("Cargar");
        b_cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_cargarMousePressed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Universos");
        treexd.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(treexd);

        b_guardar.setText("Guardar");
        b_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_guardarMousePressed(evt);
            }
        });
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuLayout.createSequentialGroup()
                        .addComponent(b_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(pb_cargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(pb_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cargar)
                    .addComponent(b_guardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Menu", menu);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Universo");

        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Seres");

        jLabel4.setText("Nombre");

        jLabel5.setText("ID:");

        jLabel6.setText("Poder:");

        spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel7.setText("Años:");

        cb_raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Amanto" }));

        jLabel8.setText("Raza");

        jLabel9.setText("Procedencia");

        jButton2.setText("Crear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton3.setText("Crear Ser");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout crearLayout = new javax.swing.GroupLayout(crear);
        crear.setLayout(crearLayout);
        crearLayout.setHorizontalGroup(
            crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(crearLayout.createSequentialGroup()
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crearLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nombreuni, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(crearLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreser)
                            .addComponent(tf_id, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_anos, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                        .addGap(48, 48, 48)
                        .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_raza, 0, 147, Short.MAX_VALUE)
                            .addComponent(cb_universos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(crearLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(107, 108, Short.MAX_VALUE))
        );
        crearLayout.setVerticalGroup(
            crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(crearLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_universos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear", crear);

        jLabel10.setText("Años:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Ser");

        cb_raza1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Amanto" }));

        jLabel12.setText("Nombre");

        jLabel13.setText("Raza");

        jLabel14.setText("ID:");

        jLabel16.setText("Poder:");

        spin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        cb_mof.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_mofItemStateChanged(evt);
            }
        });

        b_modificar.setText("Modificar");
        b_modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b_modificarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout modificarLayout = new javax.swing.GroupLayout(modificar);
        modificar.setLayout(modificarLayout);
        modificarLayout.setHorizontalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modificarLayout.createSequentialGroup()
                                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombreser1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(tf_id1)
                                    .addComponent(spin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_anos1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_raza1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_mof, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(b_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        modificarLayout.setVerticalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_mof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(spin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_anos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_raza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(b_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Modificar", modificar);

        jLabel17.setText("Nombre:");

        jLabel18.setText("ID:");

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout buscarLayout = new javax.swing.GroupLayout(buscar);
        buscar.setLayout(buscarLayout);
        buscarLayout.setHorizontalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombrebuscar)
                    .addComponent(tf_idbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addGroup(buscarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        buscarLayout.setVerticalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombrebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_idbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", buscar);

        cb_mof1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_mof1ItemStateChanged(evt);
            }
        });
        cb_mof1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mof1ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar Ser");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout eliminarLayout = new javax.swing.GroupLayout(eliminar);
        eliminar.setLayout(eliminarLayout);
        eliminarLayout.setHorizontalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarLayout.createSequentialGroup()
                .addGroup(eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eliminarLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(cb_mof1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(402, Short.MAX_VALUE))
        );
        eliminarLayout.setVerticalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(cb_mof1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", eliminar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 66, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_guardarActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        Pattern p = Pattern.compile("\\b[A-z0-9][A-z0-9_\\-\\s+]{0,40}");
        Matcher m = p.matcher(tf_nombreuni.getText());
        if(m.matches() == true){
            boolean va = true;
            for (Universo universo : u) {
                if(universo.getNombre().equals(tf_nombreuni.getText())){
                    va = false;
                }
            }
            for (Universo universo : universos) {
                if(universo.getNombre().equals(tf_nombreuni.getText())){
                    va = false;
                }
            }            
            if(va == true){
                cb_universos.removeAllItems();
                universos.add(new Universo(tf_nombreuni.getText()));
                DefaultComboBoxModel mo = (DefaultComboBoxModel)cb_universos.getModel();
                for (Universo universo : universos) {
                    mo.addElement(universo);
                }
                cb_universos.setModel(mo);
                tf_nombreuni.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "Al ya hay un universo con ese nombre creado");
            }
        }else{
            JOptionPane.showMessageDialog(this, "El Nombre del universo debe tener por lo menos un caracter alfanumerico");
        }
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
        Pattern p = Pattern.compile("\\b[A-z0-9][A-z0-9_\\-\\s+]{0,40}");
        Matcher m = p.matcher(tf_nombreser.getText());
        if(m.matches() == true){
            boolean va = true;
            try{
                if(cb_universos.getSelectedIndex() >= 0){
                    int x = Integer.parseInt(tf_id.getText());
                    boolean v = true;
                    for (Seres seres : s) {
                        if(seres.getId() == x){
                            v = false;
                        }
                    }
                    for (Seres seres : todos) {
                        if(seres.getId() == x){
                            v = false;
                        }
                    }                    
                    if(v == true){
                        todos.add(new Seres(Integer.parseInt(tf_id.getText()),tf_nombreser.getText()
                                , (Integer)spinner.getValue(), universos.get(cb_universos.getSelectedIndex()).getNombre(),
                                cb_raza.getSelectedItem().toString(), 
                                Integer.parseInt(tf_anos.getText())));
                        universos.get(cb_universos.getSelectedIndex()).getSeres().add(todos.get(todos.size()-1));
                        JOptionPane.showMessageDialog(this, "Creado con exito\n"
                                + "Presione GUARDAR en el Menu");
                        tf_nombreser.setText("");
                        tf_anos.setText("");
                        tf_id.setText("");                        
                        
                    }else{
                        JOptionPane.showMessageDialog(this, "Ya hay una persona con ese id en los arvchivos no cargados");
                    }    
                }else{
                    JOptionPane.showMessageDialog(this, "No hay Universo");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Ocurrio un error al guardar");
            }
        }else{
            JOptionPane.showMessageDialog(this, "El Nombre del Ser debe tener por lo menos un caracter alfanumerico");            
        }       
    }//GEN-LAST:event_jButton3MousePressed

    private void b_guardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_guardarMousePressed
        // TODO add your handling code here:
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        
        FileOutputStream fw1 = null;
        ObjectOutputStream bw1 = null;        
        
        try{
            general = new File(direGene+"SeresVivos.wal");
            unis = new File(direGene+"Universos.wal");
            
            fw = new FileOutputStream(unis);
            bw = new ObjectOutputStream(fw);
            for (Universo universo : universos) {
                bw.writeObject(universo);
            }
            bw.flush();
            
            fw1 = new FileOutputStream(general);
            bw1 = new ObjectOutputStream(fw1);
            for (Seres ser : todos) {
                bw1.writeObject(ser);
            }
            bw1.flush();
        }catch(Exception e){
            
        } finally {
            try {
                bw.close();
                fw.close();
                
                bw1.close();
                fw1.close();
                
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        for (Universo universo : universos) {
            String d = direuniversos+universo.getNombre()+".wal";
            File un = new File(d);
            FileOutputStream f = null;
            ObjectOutputStream b = null;
            try{
                f = new FileOutputStream(un);
                b = new ObjectOutputStream(f);
                b.writeObject(universo);                
            }catch(Exception e){
                e.printStackTrace();
            }
            try {
                b.close();
                f.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }        
        
        for (Seres ser : todos) {
            String s = direseres+ser.getId()+".wal";
            File un = new File(s);
            FileOutputStream f = null;
            ObjectOutputStream b = null;
             try{
                f = new FileOutputStream(un);
                b = new ObjectOutputStream(f);
                b.writeObject(ser);
            }catch(Exception e){
                e.printStackTrace();
            }
            try {
                b.close();
                f.close();
            } catch (Exception e) {
                e.printStackTrace();
            }           
        }        
        JOptionPane.showMessageDialog(this, "Elementos Guardados");
    }//GEN-LAST:event_b_guardarMousePressed

    private void b_cargarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cargarMousePressed
        // TODO add your handling code here:
        if(!s.isEmpty()){
            todos.addAll(s);
            pb_cargar.setMaximum(s.size());
            Hilo h = new Hilo(pb_cargar, s);
            h.start();
            s = new ArrayList<>();
            u = new ArrayList<>();
        }else{
            JOptionPane.showMessageDialog(this, "Ya se cargaron los archivos");
        }
        try{
            universos.addAll(u);
        }catch(Exception e){
            e.printStackTrace();
        }
        tree();
        
    }//GEN-LAST:event_b_cargarMousePressed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if(jTabbedPane1.getSelectedIndex() == 2){
            cb_mof.removeAllItems();
            DefaultComboBoxModel m = (DefaultComboBoxModel)cb_mof.getModel();
            for (Seres todo : todos) {
                m.addElement(todo);
            }
            cb_mof.setModel(m);
        }else if(jTabbedPane1.getSelectedIndex() == 1){
            cb_universos.removeAllItems();
            DefaultComboBoxModel mo = (DefaultComboBoxModel)cb_universos.getModel();
            for (Universo universo : universos) {
                mo.addElement(universo);
            }
            cb_universos.setModel(mo);            
        }else if(jTabbedPane1.getSelectedIndex() == 0){
            tree();
        }else if(jTabbedPane1.getSelectedIndex() == 4){
            cb_mof1.removeAllItems();
            DefaultComboBoxModel m = (DefaultComboBoxModel)cb_mof.getModel();
            for (Seres todo : todos) {
                m.addElement(todo);
            }
            cb_mof1.setModel(m);            
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void b_modificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_modificarKeyPressed
        // TODO add your handling code here:
        Pattern p = Pattern.compile("\\b[A-z0-9][A-z0-9_\\-\\s+]{0,40}");
        Matcher m = p.matcher(tf_nombreser1.getText());
        if(m.matches() == true){
            boolean va = true;
            try{
                if(cb_mof.getSelectedIndex() >= 0){
                    int x = Integer.parseInt(tf_id1.getText());
                    boolean v = true;
                    for (Seres seres : s) {
                        if(seres.getId() == x){
                            v = false;
                        }
                    }
                    for (Seres seres : todos) {
                        if(seres.getId() == x){
                            v = false;
                        }
                    }
                    int a = Integer.parseInt(tf_anos1.getText());
                    if(v == true){
                        Seres sere = todos.get(cb_mof.getSelectedIndex());
                        todos.get(cb_mof.getSelectedIndex()).setAno(a);
                        todos.get(cb_mof.getSelectedIndex()).setId(x);
                        todos.get(cb_mof.getSelectedIndex()).setRaza(cb_raza1.getItemAt(cb_raza1.getSelectedIndex()));
                        todos.get(cb_mof.getSelectedIndex()).setPoder((Integer)spin.getValue());
                        
                        //universos.get(cb_universos.getSelectedIndex()).getSeres().add(todos.get(todos.size()-1));
                        JOptionPane.showMessageDialog(this, "Modificado con exito\n"
                                + "Presione GUARDAR en el Menu");
                    }else{
                        JOptionPane.showMessageDialog(this, "Ya hay una persona con ese id en los arvchivos no cargados");
                    }    
                }else{
                    JOptionPane.showMessageDialog(this, "No hay Persona");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Ocurrio un error al Modificar");
            }
        }else{
            JOptionPane.showMessageDialog(this, "El Nombre del Ser debe tener por lo menos un caracter alfanumerico");            
        }        
    }//GEN-LAST:event_b_modificarKeyPressed

    private void cb_mofItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_mofItemStateChanged
        // TODO add your handling code here:
        if(cb_mof.getSelectedIndex() >= 0){
            Seres e = todos.get(cb_mof.getSelectedIndex());
            tf_anos1.setText(String.valueOf(e.getAno()));
            tf_id1.setText(String.valueOf(e.getId()));
            tf_nombreser1.setText(e.getNombre());
            spin.setValue(e.getPoder());
            if(e.getRaza().equalsIgnoreCase("Humano")){
                cb_raza1.setSelectedIndex(0);
            }else{
                cb_raza1.setSelectedIndex(1);
            }
        }
    }//GEN-LAST:event_cb_mofItemStateChanged

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        boolean v = false;
        if(!tf_idbuscar.getText().isBlank() || !tf_idbuscar.getText().isEmpty()){
            try {
                int x = Integer.parseInt(tf_idbuscar.getText());

                for (Seres seres : s) {
                    if(seres.getId() == x){
                        v = true;
                    }
                }
                for (Seres seres : todos) {
                    if(seres.getId() == x){
                        v = true;
                    }
                }         
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "ID erroneo");
            }
        }   
        if(v == true){
            JOptionPane.showMessageDialog(this, "Se encontro una persona con el ID");
        }else{
            String d = tf_nombrebuscar.getText();
            for (Seres seres : s) {
                if(seres.getNombre().equals(d)){
                    v = true;
                }
            }
            for (Seres seres : todos) {
                if(seres.getNombre().equals(d)){
                    v = true;
                }
            } 
            if(v == true){
                JOptionPane.showMessageDialog(this, "Se encontro una persona con ese nombre");
            }else{
                JOptionPane.showMessageDialog(this, "No se encontro a nadie");
            }
        }
    }//GEN-LAST:event_jButton1MousePressed

    private void cb_mof1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_mof1ItemStateChanged
        if(cb_mof1.getSelectedIndex() >= 0){
            Seres e = todos.get(cb_mof1.getSelectedIndex());
            tf_anos1.setText(String.valueOf(e.getAno()));
            tf_id1.setText(String.valueOf(e.getId()));
            tf_nombreser1.setText(e.getNombre());
            spin.setValue(e.getPoder());
            if(e.getRaza().equalsIgnoreCase("Humano")){
                cb_raza1.setSelectedIndex(0);
            }else{
                cb_raza1.setSelectedIndex(1);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_mof1ItemStateChanged

    private void cb_mof1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mof1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_mof1ActionPerformed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
             
    }//GEN-LAST:event_jButton4MousePressed

    private void tree(){      
        treexd = new JTree();
        DefaultMutableTreeNode nodo = new DefaultMutableTreeNode("Universos");
        treexd.setModel(new DefaultTreeModel(nodo));
        
        DefaultTreeModel m = (DefaultTreeModel)treexd.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        for (Universo universo : universos) {
            System.out.println(universo);
            DefaultMutableTreeNode unn = new DefaultMutableTreeNode(universo);
            for (Seres sere : universo.getSeres()) {
                DefaultMutableTreeNode c = new DefaultMutableTreeNode(sere);
                unn.add(c);
            }
            raiz.add(unn);
        }
        treexd.setModel(m);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    ArrayList<Universo> universos = new ArrayList<>();
    ArrayList<Seres> todos = new ArrayList<>();
    
    File general = null;
    File unis = null;
    String direGene = "./Carpetas/General/";
    
    File ser = null;
    String direseres = "./Carpetas/Seres/";
    
    File uni = null;
    String direuniversos = "./Carpetas/Universos/";
    
    ArrayList<Universo> u = new ArrayList<>();
    ArrayList<Seres> s = new ArrayList<>();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cargar;
    private javax.swing.JButton b_guardar;
    private javax.swing.JButton b_modificar;
    private javax.swing.JPanel buscar;
    private javax.swing.JComboBox<String> cb_mof;
    private javax.swing.JComboBox<String> cb_mof1;
    private javax.swing.JComboBox<String> cb_raza;
    private javax.swing.JComboBox<String> cb_raza1;
    private javax.swing.JComboBox<String> cb_universos;
    private javax.swing.JPanel crear;
    private javax.swing.JPanel eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel modificar;
    private javax.swing.JProgressBar pb_cargar;
    private javax.swing.JSpinner spin;
    private javax.swing.JSpinner spinner;
    private javax.swing.JTextField tf_anos;
    private javax.swing.JTextField tf_anos1;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JTextField tf_idbuscar;
    private javax.swing.JTextField tf_nombrebuscar;
    private javax.swing.JTextField tf_nombreser;
    private javax.swing.JTextField tf_nombreser1;
    private javax.swing.JTextField tf_nombreuni;
    private javax.swing.JTree treexd;
    // End of variables declaration//GEN-END:variables
}
